repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --exit-non-zero-on-fix ]
      # Run the formatter.
      - id: ruff-format
